twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        # the value is the service's id
        navList: '@App\Service\NavList'
when@test:
    twig:
        strict_variables: true
